### ISSUE TITLE
'pam_unix(passwd:chauthtok): user "{user}" does not exist in /etc/passwd'

### ISSUE THREAD

**Issue by pddg** [linyows/octopass#21]
I am using VPS service of SAKURA internet. And system information is as follows.

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
$ uname -r -v
4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017
```

I installed `octopass` into it and success to login via ssh with my github account (`pddg`).   (Issue title's `{user}` is a placeholder. My account name is `pddg`) 

First, when I use `sudo` in order to modify any configuration files, the system required password for `pddg`. I tried to input password of my github account, but `Sorry, try again.`.   
 
Second, I used `passwd` command to set password for `pddg`, but the command said as follows.

```bash
$ passwd pddg
passwd: Authentication token manipulation error
passwd: password unchanged
```

I tried to use `pwconv` and `pwunconv` from other account in SAKURA's control panel (it created before installing octopass). But `passwd` command fail with same messages.   

Configuration and log files are as follows.

`/var/log/auth.log` 

```bash
Dec 10 15:25:00 aqua octopass[1492]: pam_unix(sshd:session): session opened foruser pddg by (uid=0)
Dec 10 15:25:00 aqua octopass[1497]: pam_unix(systemd-user:session): session opened for user pddg by (uid=0)
Dec 10 15:25:00 aqua systemd-logind[542]: New session 6 of user pddg.
Dec 10 15:25:04 aqua octopass[1535]: pam_unix(passwd:chauthtok): user "pddg" does not exist in /etc/passwd
Dec 10 15:25:29 aqua octopass[1537]: pam_unix(sudo:auth): authentication failure; logname=pddg uid=14107201 euid=0 tty=/dev/pts/0 ruser=pddg rhost=  user=pddg
Dec 10 15:25:33 aqua octopass[1537]: pam_unix(sudo:auth): auth could not identify password for [pddg]
Dec 10 15:25:33 aqua sudo:     pddg : 1 incorrect password attempt ; TTY=pts/0 ; PWD=/home/pddg ; USER=root ; COMMAND=/usr/bin/vim
```

`/etc/pam.d/sshd`

```bash
#@include common-auth
auth requisite pam_exec.so quiet expose_authtok /usr/bin/octopass pam
auth optional pam_unix.so not_set_pass use_first_pass nodelay
session required pam_mkhomedir.so skel=/etc/skel/ umask=0022
account    required     pam_nologin.so
```

`/etc/nsswitch.conf`

```bash
passwd:     files octopass sss
shadow:     files octopass sss
group:      files octopass sss
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

How do I use command with `sudo` from an user authenticated by octopass?

**Comment by linyows** [comment]
Octopass resolves linux user name resolution. So, sudo management is generally done with sudoers. Please set sudo permission in user / group etc under `/etc/sudoers.d/`. Example [here](https://github.com/linyows/octopass-cookbook/blob/master/templates/default/sudoers.d-octopass.erb).

Thank you for using octopass.

**Comment by pddg** [comment]
Thank you! I came to be able to use `sudo`．

Octopass is very nice tool for small team. But I would be nice to use its feature with multiple role, for example, a beginner to practice to operate server without `sudo` or an administrator... etc, separated by Github Team. Do you plan it?

**Comment by linyows** [comment]
@pddg I have an idea of supporting more than one team than before, but at the moment the priority is not high.

**Comment by pddg** [comment]
@linyows I understand it.

I am looking forward to implementing it!
