### ISSUE TITLE
add octopass users to other llinux groups, e.g. docker

### ISSUE THREAD

**Issue by sergpolly** [linyows/octopass#32]
This is about new feature - not an issue!

I'm trying to figure out now how to add the whole `octopass`-group to another linux groups - e.g. `docker` to let users have access to `docker` without root ...
I think, this https://github.com/linyows/octopass/issues/21 would not work for this case because `sudoers` is a special group, right ?

following works, but it's not dynamic - would require rerun after adding new users to github team:
```bash
for user in `sudo octopass passwd | cut -f1 -d':'`;
   do sudo usermod -aG docker $user;
done
```

I'll try to read `octopass` code and see how additional groups can be done.

**Comment by linyows** [comment]
It is a good proporsal. I will do this.

**Comment by linyows** [comment]
When adding a user provided by octopass to another group, it is necessary to register in another database (e.g. `/etc/passwd`), so it seems that it can not be done by octopass side implementation. Conversely, it is feasible to have users in other databases belong to the octopass group.

**Comment by linyows** [comment]
How about sudo with user specified? Like this: `sudo -u docker docker build -t foo .` It's a bother...

**Comment by sergpolly** [comment]
I'd need to read about `sudo ` with `-u` option , I don't know what it does...
Also, I wouldn't want to let our users to becomes sudoers - people would start `sudo apt installing` things for no reason))

I was also thinking about changing ownership of the `docket` socket `/var/run/docker.sock` to the octopass group - that would solve it for our use case. I haven't tried it yet.

Docker socket ownership is described here a bit:
https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by sergpolly** [comment]
I had no idea this was possible : https://unix.stackexchange.com/questions/215412/allow-certain-guests-to-execute-certain-commands

That means I can use #21 allowing octopass team to run only `sudo docker ...` and not `sudo rm -rf ...` for example?!

**Comment by linyows** [comment]
That's right. Example:

```sh
$ cat /etc/sudoers.d/dekkerlab-main
dekkerlab-main ALL=(root) NOPASSWD:/usr/bin/docker
```

**Comment by linyows** [comment]
Now you can only run docker command as root with sudo

**Comment by sergpolly** [comment]
That sounds like what we need exactly!
I'll try it tomorrow (in ~10 hours).
Thank you so much, again!

**Comment by sergpolly** [comment]
after adding `%` before the group-name `%dekkerlab-main` - and `chmod 0440 /etc/sudoers.d/dekkerlab-main` everything worked!
