### ISSUE TITLE
segfault when freeing memory (ubuntu 20.04)

### ISSUE THREAD

**Issue by djeebus** [linyows/octopass#41]
First of all, thanks for the great tool!

When installing it on Ubuntu 20.04, I'm running into a similar issue as #30 . All is good when I install/configure it, but when I reboot the server, the network interface doesn't come up, due to various network related systemd services segfaulting (for example, systemd-timesyncd, and systemd-networkd). 

Following your commands in #31, I found that it was segfaulting when calling `free(res.data)` in `_nss_octopass_getpwnam_r_locked`. I tried wrapping those calls in `if (res.data) { free(res.data); }`, but after recompiling I got similar segfaults in `_nss_octopass_setgrent_locked` for `free(res.data)`, and wrapping those didn't fix the segfaults. Removing all the calls to `free` does get the code to continue on, but that's probably not a good long term solution. 

This can be reproduced by configuring octopass on an unmodified Ubuntu 20.04 server installation.

Here's an example of a coredump after wrapping all calls to `free`, but before removing them completely:
```
djeebus@testlinux:~$ sudo coredumpctl gdb 1196
           PID: 1196 ((imesyncd))
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Thu 2021-02-04 19:58:07 UTC (29min ago)
  Command Line: (imesyncd)
    Executable: /usr/lib/systemd/systemd
 Control Group: /system.slice/systemd-timesyncd.service
          Unit: systemd-timesyncd.service
         Slice: system.slice
       Boot ID: 7b20e878394d477495b811a9464a508b
    Machine ID: aef939b5729e4732a639a868bb2d8a09
      Hostname: testlinux
       Storage: /var/lib/systemd/coredump/core.(imesyncd).0.7b20e878394d477495b811a9464a508b.1196.1612468687000000000000.lz4
       Message: Process 1196 ((imesyncd)) of user 0 dumped core.

                Stack trace of thread 1196:
                #0  0x00007fde9484c870 __GI___libc_free (libc.so.6 + 0x9d870)
                #1  0x00007fde939a6861 _nss_octopass_setgrent_locked (libnss_octopass.so.2 + 0x8861)
                #2  0x00007fde939a69d2 _nss_octopass_setgrent (libnss_octopass.so.2 + 0x89d2)
                #3  0x00007fde94890e69 compat_call (libc.so.6 + 0xe1e69)
                #4  0x00007fde948912b9 internal_getgrouplist (libc.so.6 + 0xe22b9)
                #5  0x00007fde948914cf initgroups (libc.so.6 + 0xe24cf)
                #6  0x000055e67a48465b n/a (systemd + 0x4565b)
                #7  0x000055e67a5146f2 n/a (systemd + 0xd56f2)
                #8  0x000055e67a4dd446 n/a (systemd + 0x9e446)
                #9  0x000055e67a4e1f05 n/a (systemd + 0xa2f05)
                #10 0x000055e67a4e24b8 n/a (systemd + 0xa34b8)
                #11 0x000055e67a50ab8c n/a (systemd + 0xcbb8c)
                #12 0x000055e67a4efcda n/a (systemd + 0xb0cda)
                #13 0x00007fde945ccad2 n/a (libsystemd-shared-245.so + 0x76ad2)
                #14 0x00007fde945ccef1 sd_event_dispatch (libsystemd-shared-245.so + 0x76ef1)
                #15 0x00007fde945ce928 sd_event_run (libsystemd-shared-245.so + 0x78928)
                #16 0x000055e67a52b095 n/a (systemd + 0xec095)
                #17 0x000055e67a47b7e3 n/a (systemd + 0x3c7e3)
                #18 0x00007fde947d60b3 __libc_start_main (libc.so.6 + 0x270b3)
                #19 0x000055e67a47ca7e n/a (systemd + 0x3da7e)
```

Once again, thanks!

**Comment by djeebus** [comment]
After wrapping all of the `free(res.data)` calls and removing the `free(res.data)` call on line 73 of nss_octopass-group.c, these are the debug logs when calling `sudo systemctl restart systemd-timesyncd`:

Feb 04 21:44:57 testlinux octopass[2739]: config {endpoint: https://api.github.com/, token: bf10e ************ REDACTED ************, organization: Hatch1fy, team: server-admins, owner: Hatch1fy, repository: , permission:  syslog: 1, uid_starts: 2000, gid: 2000, group_name: github, home: /home/github/%s, shell: /bin/bash, cache: 300}
Feb 04 21:44:57 testlinux octopass[2739]: _nss_octopass_setgrent_locked[L68] -- stayopen: -670258774
Feb 04 21:44:57 testlinux octopass[2739]: use cache: /var/cache/octopass/0/https%3A%2F%2Fapi.github.com%2Forgs%2FHatch1fy%2Fteams%3Fper_page%3D100-bf10ee
Feb 04 21:44:57 testlinux octopass[2739]: use cache: /var/cache/octopass/0/https%3A%2F%2Fapi.github.com%2Fteams%2F4470359%2Fmembers%3Fper_page%3D100-bf10ee
Feb 04 21:44:57 testlinux octopass[2739]: config {endpoint: https://api.github.com/, token: bf10e ************ REDACTED ************, organization: Hatch1fy, team: server-admins, owner: Hatch1fy, repository: , permission:  syslog: 1, uid_starts: 2000, gid: 2000, group_name: github, home: /home/github/%s, shell: /bin/bash, cache: 300}
Feb 04 21:44:57 testlinux octopass[2739]: _nss_octopass_getgrent_r_locked[L162]
Feb 04 21:44:57 testlinux octopass[2739]: _nss_octopass_getgrent_r_locked[L183] -- status: SUCCESS, gr_name: github
Feb 04 21:44:57 testlinux sudo[2739]:      joe : TTY=tty1 ; PWD=/home/joe/octopass ; USER=root ; COMMAND=/usr/bin/systemctl restart systemd-timesyncd
Feb 04 21:44:57 testlinux octopass[2739]: config {endpoint: https://api.github.com/, token: bf10e ************ REDACTED ************, organization: Hatch1fy, team: server-admins, owner: Hatch1fy, repository: , permission:  syslog: 1, uid_starts: 2000, gid: 2000, group_name: github, home: /home/github/%s, shell: /bin/bash, cache: 300}
Feb 04 21:44:57 testlinux octopass[2739]: _nss_octopass_setgrent_locked[L68] -- stayopen: -670258774
Feb 04 21:44:57 testlinux octopass[2739]: use cache: /var/cache/octopass/0/https%3A%2F%2Fapi.github.com%2Forgs%2FHatch1fy%2Fteams%3Fper_page%3D100-bf10ee
Feb 04 21:44:57 testlinux octopass[2739]: use cache: /var/cache/octopass/0/https%3A%2F%2Fapi.github.com%2Fteams%2F4470359%2Fmembers%3Fper_page%3D100-bf10ee
Feb 04 21:44:57 testlinux octopass[2739]: config {endpoint: https://api.github.com/, token: bf10e ************ REDACTED ************, organization: Hatch1fy, team: server-admins, owner: Hatch1fy, repository: , permission:  syslog: 1, uid_starts: 2000, gid: 2000, group_name: github, home: /home/github/%s, shell: /bin/bash, cache: 300}
Feb 04 21:44:57 testlinux octopass[2739]: _nss_octopass_getgrent_r_locked[L162]
Feb 04 21:44:57 testlinux octopass[2739]: _nss_octopass_getgrent_r_locked[L183] -- status: SUCCESS, gr_name: github
Feb 04 21:44:57 testlinux octopass[2739]: pam_unix(sudo:session): session opened for user root by joe(uid=0)
Feb 04 21:44:57 testlinux systemd[1]: Stopping Network Time Synchronization...
Feb 04 21:44:57 testlinux systemd[1]: systemd-timesyncd.service: Succeeded.
Feb 04 21:44:57 testlinux systemd[1]: Stopped Network Time Synchronization.
Feb 04 21:44:57 testlinux systemd[1]: Starting Network Time Synchronization...
Feb 04 21:44:57 testlinux octopass[2744]: [286B blob data]
Feb 04 21:44:57 testlinux octopass[2744]: _nss_octopass_setgrent_locked[L68] -- stayopen: -843220566
Feb 04 21:44:57 testlinux octopass[2744]: use cache: /var/cache/octopass/0/https%3A%2F%2Fapi.github.com%2Forgs%2FHatch1fy%2Fteams%3Fper_page%3D100-bf10ee
Feb 04 21:44:57 testlinux octopass[2744]: team not found: server-admins
Feb 04 21:44:57 testlinux octopass[2744]: _nss_octopass_setgrent_locked[L74] -- status: UNAVAIL
Feb 04 21:44:57 testlinux systemd[1]: Started Network Time Synchronization.
Feb 04 21:44:57 testlinux octopass[2739]: pam_unix(sudo:session): session closed for user root
Feb 04 21:44:57 testlinux systemd-timesyncd[2744]: Initial synchronization to time server 192.168.1.12:123 (192.168.1.12).
Feb 04 21:45:01 testlinux PackageKit[2663]: daemon quit
Feb 04 21:45:01 testlinux systemd[1]: packagekit.service: Succeeded.
```

The "status: UNAVAIL" and "team not found: server-admins" lines are the ones being prevented from rendering on the segfault, I believe. They're also interesting b/c "server-admins" is definitely the right team, and that cache file referenced above definitely contains a valid list of users from that team AND ssh actually works correctly. Very strange.

**Comment by linyows** [comment]
@djeebus Sorry for the late response. Maybe the #42 change solves this problem.
